### ISSUE TITLE
Multiqueries problem

### ISSUE THREAD

**Issue by dariuszlacheta** [keen/keen-analysis.js#64] opened 2019-07-10 10:25 UTC
When multiqueries run with the same analysis_type for the same event_collection, both names are equal and this is causing problems with keen-dataviz.

**Comment by adamkasprowicz** [comment] 2019-07-10 14:48
so in our case we'll check if:
if (JSON.stringify of query params 1 !== JSON.stringify if query params 2)
let's add a number at the end of the name of query

so in this example keen-analysis would return something like
count pageviews 1
count pageviews 2

to be more precise can add a name describing the difference between them. For example if the only difference is the filter:
for the first query: where user.id = 123
for the second query: where user.id = 555

the name for this query should be:
count pageviews where user.id = 123
count pageviews where user.id = 555

**Comment by maciejrybaniec** [comment] 2019-12-09 14:11
Duplicate of #61

**Closed by maciejrybaniec** 2019-12-09 14:11 UTC
